app:
  security:
    sso-base-url: https://ssodev.muenchen.de
    realm: A23
    introspection-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}/protocol/openid-connect/token/introspect
    authorization-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}/protocol/openid-connect/auth
    token-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}/protocol/openid-connect/token
    api:
      client-id: instikom-kf-schnittstelle
      # app.security.client-secret: required for oauth authentication to work.
      # Add in programm arguments or environment
    internal:
      client-id: kf-app-eai-internal
      # app.security.client-secret: required for oauth authentication to work.
      # Add in programm arguments or environment
  passwordEncoder:
    # Encryption properties. Overwrite in non-dev-environments!
    encryptor:
      password: 377b88361dd70f30689cecf46e73e36d
      salt: 2c82deb3e67b0da1
  kitafinderAdapter:
    baseUrl: http://kitafinder-plan-k2.muenchen.de
      
spring:
  application:
    name: kita-finder-eai
          
# swagger-ui configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      clientId: ${app.security.api.client-id}
      realm: ${app.security.realm}
      appName: ${spring.application.name}
      scopes:
      - acr
      - email
      - profile
      - roles
      - web-origins
  default-produces-media-type: application/json
  
server:
  port: 8080
