app:
  db:
    url: jdbc:h2:mem:testdb
    user: kf_app_eai
    schema: PUBLIC
    # password: todo 
  security:
    sso-base-url: https://ssodev.muenchen.de
    realm: A23
    authorization-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}/protocol/openid-connect/auth
    token-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}/protocol/openid-connect/token
    issuer-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}
    client-id: kf-app-eai
  passwordEncoder:
    # Encryption properties. Overwrite in non-dev-environments!
    encryptor:
      password: 377b88361dd70f30689cecf46e73e36d
      salt: 2c82deb3e67b0da1
  kitafinderAdapter:
    baseUrl: http://kitafinder-plan-k2.muenchen.de
    exportRelativeUrl: /kitaplaner/api/schnittstelle/export

spring:
  profiles:
    active: # default profiles
      - no-security
  # Spring Data
  application:
    name: kf-app-eai
  flyway:
    default-schema: ${app.db.schema}
  datasource:
    url: ${app.db.url}
    username: ${app.db.user}
    password: ${app.db.password}
    hikari:
      schema: ${app.db.schema}
          
# swagger-ui configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      realm: ${app.security.realm}
      appName: ${spring.application.name}
      scopes:
      - LHM_Extended
      - roles
      - openid
  default-produces-media-type: application/json
  
server:
  port: 8080
