CREATE TABLE KITA_DATA (
    KIBIGWEB_ID VARCHAR(255), 
    PASSWORD VARCHAR(255), 
    KITA_ID_EXTERN VARCHAR(255), 
    TRAEGER VARCHAR(255),
    LAST_CHANGED_AT TIMESTAMP,
    LAST_CHANGED_BY VARCHAR(255)
);