CREATE TABLE KITA_DATA (
    KIBIGWEB_ID VARCHAR(255), 
    PASSWORD VARCHAR(255), 
    KITA_ID_EXTERN VARCHAR(255), 
    TRAEGER VARCHAR(255),
    LAST_CHANGED_AT TIMESTAMP,
    LAST_CHANGED_BY VARCHAR(255)
);

CREATE TABLE AUD_REQ_RES (
    ID UUID,
    REQ_KIBIGWEB_ID VARCHAR(255), 
    RSLV_KITA_ID_EXTERN VARCHAR(255), 
    RSLV_TRAEGER VARCHAR(255), 
    RES_HTTP_STATUS_CODE VARCHAR(255),
    RES_ERROR VARCHAR(255),
    RES_ERROR_DETAIL VARCHAR(255),
    RES_ERROR_MESSAGE VARCHAR(255),
    ERROR_TRACE VARCHAR(255),
    CREATED_AT TIMESTAMP
);